### ISSUE TITLE
won't start on Ubuntu 22.04

### ISSUE THREAD

**Issue by amsteel** [hhannine/superpaper#117]
ubuntu 22.04 fresh install with superpaper, after click ok it crashed.

**Expected behavior**
should start and show main windows

**Screenshots**

![Screenshot from 2022-04-27 14-33-16](https://user-images.githubusercontent.com/16197031/165597056-8e9a3108-eb1d-4a73-bcb3-f994f842edd0.png)

**Desktop (please complete the following information):**
Ubuntu 22.04

Logging / debugging contents:
------------------
None
None
None
None
None
None
True
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')

(superpaper:16878): Gtk-CRITICAL **: 14:38:46.768: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND2')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND1')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND2')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat
START Listing profiles for menu.
hkBinding: ('control', 'super', 'shift', 'h')
Listed profile: example
hkBinding: ('control', 'super', 'shift', 'g')
Listed profile: example_multi
END Listing profiles for menu.
No previous profile was found.
Exception ignored in thread started by: <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7ff644504520>>
Traceback (most recent call last):
  File "/home/amsteel/.local/lib/python3.10/site-packages/system_hotkey/util.py", line 37, in call_functions
hkBinding: ('control', 'super', 'shift', 'h')
    func(*args, **kwargs)
  File "/home/amsteel/.local/lib/python3.10/site-packages/system_hotkey/system_hotkey.py", line 284, in register
    assert isinstance(hotkey, collections.Iterable) and type(hotkey) not in (str, bytes)
AttributeError: module 'collections' has no attribute 'Iterable'
Listed profile: example
hkBinding: ('control', 'super', 'shift', 'g')
Listed profile: example_multi
Registering binding:                                 ('control', 'super', 'shift', 'h') for profile: example
Registering binding:                                 ('control', 'super', 'shift', 'g') for profile: example_multi
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
WARNING: Horizontal and vertical PPI do not match! hor: 127.74852652259331, ver: 95.9160839160839
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=None, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND2')
get_display_data output: NUM_DISPLAYS = 3, RES_ARR = [(1920, 1080), (1920, 1080), (2560, 1080)], OFF_ARR = [(0, 0), (1920, 0), (3840, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND1')
Display(resolution=(1920, 1080), digital_offset=(1920, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=95.81139489194499, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND0')
Display(resolution=(2560, 1080), digital_offset=(3840, 0), phys_size_mm=(509, 286), detected_phys_size_mm=(509, 286), ppi=127.74852652259331, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='XWAYLAND2')
load_system: archive_file not found: /home/amsteel/.config/superpaper/display_systems.dat
Traceback (most recent call last):
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper/tray.py", line 472, in OnInit
    TaskBarIcon(frame)
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper/tray.py", line 115, in __init__
    config_frame = ConfigFrame(self)
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper/gui.py", line 31, in __init__
    config_panel = WallpaperSettingsPanel(self, parent_tray_obj)
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper/gui.py", line 74, in __init__
    self.wpprev_pnl = WallpaperPreviewPanel(self, self.display_sys)
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper/gui.py", line 1363, in __init__
    self.draw_displays()
  File "/home/amsteel/.local/lib/python3.10/site-packages/superpaper/gui.py", line 1381, in draw_displays
    bmp_canv = wx.Bitmap.FromRGBA(self.dtop_canvas_relsz[0], self.dtop_canvas_relsz[1], red=0, green=0, blue=0, alpha=255)
TypeError: Bitmap.FromRGBA(): argument 1 has unexpected type 'float'
/home/amsteel/.local/lib/python3.10/site-packages
/home/amsteel/.config/superpaper
/home/amsteel/.config/superpaper/profiles
OnInit returned false, exiting...
-----------------------------------

**Comment by Findarato** [comment]
Adding a bit, this is from Fedora 36 installed from pip on python 3.10

```
Exception ignored in thread started by: <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7f6319370640>>
Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.10/site-packages/system_hotkey/util.py", line 37, in call_functions
    func(*args, **kwargs)
  File "/home/joe/.local/lib/python3.10/site-packages/system_hotkey/system_hotkey.py", line 284, in register
    assert isinstance(hotkey, collections.Iterable) and type(hotkey) not in (str, bytes)
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by hhannine** [comment]
The unexpected type errors seen in your log @amsteel have been fixed in master here at Github. You could clone and install the up to date repo copy to fix this, before I can get to releasing a new version.

**Comment by amsteel** [comment]
it runs and shows the wall paper in the GUI. However it won't update the wall paper in desktop. Here are the errors:
(__main__.py:788127): Gtk-WARNING **: 15:55:50.560: Error loading theme icon 'dialog-question' for stock: Icon 'dialog-question' not present in theme candy-icons

(__main__.py:788127): Gtk-CRITICAL **: 15:56:13.460: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed

(__main__.py:788127): Gtk-WARNING **: 15:56:17.733: Error loading theme icon 'media-floppy' for stock: Icon 'media-floppy' not present in theme candy-icons

(__main__.py:788127): Gtk-WARNING **: 15:56:17.747: Error loading theme icon 'system-run' for stock: Icon 'system-run' not present in theme candy-icons

(__main__.py:788127): Gtk-CRITICAL **: 15:57:14.890: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed

(__main__.py:788127): Gtk-CRITICAL **: 15:57:21.788: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed

(__main__.py:788127): Gtk-CRITICAL **: 15:58:23.137: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed

(__main__.py:788127): Gtk-CRITICAL **: 15:59:51.624: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed

(__main__.py:788127): Gtk-CRITICAL **: 16:00:01.605: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
