### ISSUE TITLE
"Your DE could not be detected to set the wallpaper."

### ISSUE THREAD

**Issue by Ch-Rad** [hhannine/superpaper#118]
**Describe the bug**
I am able to make a profile and set it up accordingly but when i apply it the app crashes after a while and does not set the wallpapers as I had set it. I also don't know what to set in "set_command" option. This is my settings file:
`
logging=false

use hotkeys=true

next wallpaper hotkey=control+super+w

pause wallpaper hotkey=control+super+shift+p

set_command=

browse_default_dir=

warn_large_img=true
`

**To Reproduce**
1. Open the app with "--debug"
2. Make a profile
3. Apply the profile
4. See the error in the terminal and see the app is not responding then crashing

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Desktop Environment on Linux: Gnome 42
 - Superpaper package & version: AppImage

Logging / debugging contents:
```
`./Superpaper-2.1.0-x86_64.AppImage --debug
/tmp/.mount_SuperprLOJxR/usr
/home/vicky/.config/superpaper
/home/vicky/.config/superpaper/profiles
None
None
None
None
None
None
True
/usr/lib64/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
09:08:01 PM: Debug: Failed to connect to session manager: None of the authentication protocols specified are supported
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
GeneralSettings parse Exception: Unkown general setting: 
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1366, 768)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(345, 195), detected_phys_size_mm=(345, 195), ppi=141.35652173913041, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-0')
Display(resolution=(1366, 768), digital_offset=(1920, 0), phys_size_mm=(409, 230), detected_phys_size_mm=(409, 230), ppi=84.83227383863081, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
load_system: archive_file not found: /home/vicky/.config/superpaper/display_systems.dat
START Listing profiles for menu.
Listed profile: new1
END Listing profiles for menu.
read profile name from 'running_profile': new1
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1366, 768)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(345, 195), detected_phys_size_mm=(345, 195), ppi=141.35652173913041, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-0')
Display(resolution=(1366, 768), digital_offset=(1920, 0), phys_size_mm=(409, 230), detected_phys_size_mm=(409, 230), ppi=84.83227383863081, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
load_system: archive_file not found: /home/vicky/.config/superpaper/display_systems.dat
running profile job with profile: new1
Running a one-off wallpaper change.
['/home/vicky/Pictures/Wallpapers/wallpaperflare.com_WLOP.jpg', '/home/vicky/Pictures/Wallpapers/wallpaperflare.com_focus.jpg']
Canvas size: [3286, 1080]
Unhandled exception in thread started by <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7f06bee5df60>>
Traceback (most recent call last):
  File "system_hotkey/system_hotkey.py", line 756, in _xcb_the_grab
  File "xcffib/__init__.py", line 339, in check
  File "xcffib/__init__.py", line 571, in wrapper
  File "xcffib/__init__.py", line 680, in request_check
Listed profile: new1
Registering binding:                                 None for profile: new1
  File "xcffib/__init__.py", line 648, in _process_error
xcffib.xproto.AccessError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "system_hotkey/util.py", line 37, in call_functions
  File "system_hotkey/system_hotkey.py", line 307, in register
  File "system_hotkey/system_hotkey.py", line 763, in _xcb_the_grab
system_hotkey.system_hotkey.SystemRegisterError: The bind could be in use elsewhere: w
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
GeneralSettings parse Exception: Unkown general setting: 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "superpaper/wallpaper_processing.py", line 1328, in set_multi_image_wallpaper
IndexError: list index out of range

get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1366, 768)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(345, 195), detected_phys_size_mm=(345, 195), ppi=141.35652173913041, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-0')
Display(resolution=(1366, 768), digital_offset=(1920, 0), phys_size_mm=(409, 230), detected_phys_size_mm=(409, 230), ppi=84.83227383863081, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
load_system: archive_file not found: /home/vicky/.config/superpaper/display_systems.dat

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.750: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.764: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.764: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.766: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.766: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.768: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.768: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.770: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.770: Loading IM context type 'ibus' failed
Listed profile: new1

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.773: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.773: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.780: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.780: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.783: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.783: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.787: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.787: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.788: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.788: Loading IM context type 'ibus' failed
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
GeneralSettings parse Exception: Unkown general setting: 

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.803: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.803: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.806: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.806: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.807: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.807: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.816: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.816: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.817: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.817: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.818: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.818: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.818: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.818: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.819: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.819: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.819: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.819: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.820: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.820: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.821: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:01.821: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:08.275: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:08.275: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:08.276: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:08.276: Loading IM context type 'ibus' failed

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:08.279: /lib64/libibus-1.0.so.5: undefined symbol: g_get_language_names_with_category

(Superpaper-2.1.0-x86_64.AppImage:39585): Gtk-WARNING **: 21:08:08.279: Loading IM context type 'ibus' failed
new1
multi
False
None
None
None
None
['/home/vicky/Pictures/Wallpapers/wallpaperflare.com_WLOP.jpg', '/home/vicky/Pictures/Wallpapers/wallpaperflare.com_focus.jpg']
perspective preset: default
Listed profile: new1
perspective preset: default
Listed profile: new1
Unreg hotkey ('control', 'super', 'shift', 'p')
Unreg hotkey ('control', 'super', 'w')
perspective preset: default
Listed profile: new1
Registering binding:                                 None for profile: new1
perspective preset: default
onApply profile: saved /home/vicky/.config/superpaper/profiles/new1.profile
perspective preset: default
perspective preset: default
Listed profile: new1
Start profile: new1
Check if the starting profile is already running: new1
name check: new1, new1
Running quick profile job with profile: new1
quickswitch file lookup: ['new1-a.png', 'new1-b.png']
file:///home/vicky/.cache/superpaper/temp/new1-a.png
Starting timed profile job with profile: new1
DESKTOP_SESSION is: 'gnome-xorg'
Your DE could not be detected to set the wallpaper. You need to set the 'set_command' option in your settings file superpaper/general_settings. Exiting.
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (1366, 768)], OFF_ARR = [(0, 0), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 0), phys_size_mm=(345, 195), detected_phys_size_mm=(345, 195), ppi=141.35652173913041, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-0')
Display(resolution=(1366, 768), digital_offset=(1920, 0), phys_size_mm=(409, 230), detected_phys_size_mm=(409, 230), ppi=84.83227383863081, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='DP-1')
load_system: archive_file not found: /home/vicky/.config/superpaper/display_systems.dat
running profile job with profile: new1
Running a one-off wallpaper change.
['/home/vicky/Pictures/Wallpapers/wallpaperflare.com_WLOP.jpg', '/home/vicky/Pictures/Wallpapers/wallpaperflare.com_focus.jpg']
Wrote active profile: new1
Canvas size: [3286, 1080]
file:///home/vicky/.cache/superpaper/temp/new1-b.png
DESKTOP_SESSION is: 'gnome-xorg'
Your DE could not be detected to set the wallpaper. You need to set the 'set_command' option in your settings file superpaper/general_settings. Exiting.
Killed
`

**Comment by hhannine** [comment]
The DE detection problem has already been fixed in master actually, so you could clone and install that to get the fix.
To workaround the DE detection, you can run Superpaper with the command
`DESKTOP_SESSION=gnome ./Superpaper`

Your system is probably using Python 3.10 or newer so check #102 

I'll close this as this specific issue has been fixed, but create a new issue if you still run into something.
