### ISSUE TITLE
Wont's start on Linuxmint 20.3, Cinnamon 5.2.7

### ISSUE THREAD

**Issue by BerekHalfhand** [hhannine/superpaper#134]
**Describe the bug**
App crashes on startup, saying 
AttributeError: 'NoneType' object has no attribute 'name

**To Reproduce**
1. get Linuxmint 20.3, Cinnamon 5.2.7
2. try following the steps, install thru python3
3. try launching

**Expected behavior**
Expected to run

**Desktop (please complete the following information):**
 - OS: Linuxmint 20.3,
 - Desktop Environment on Linux: Cinnamon 5.2.7
 - Superpaper package & version: 2.2.0

**Additional context**
I have to remove the package now because it wrecked my wallpapers

Logging / debugging contents:
```
superpaper --debug
/home/maat-re/.local/lib/python3.8/site-packages
/home/maat-re/.config/superpaper
/home/maat-re/.config/superpaper/profiles
Input images: None
Input profile: None
Input perspective: None
Input spangroups: None
Input offsets: None
User defined command: None
Debugging: True
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
get_display_data output: NUM_DISPLAYS = 2, RES_ARR = [(1920, 1080), (3840, 2160)], OFF_ARR = [(0, 1080), (1920, 0)]
Display(resolution=(1920, 1080), digital_offset=(0, 1080), phys_size_mm=(344, 194), detected_phys_size_mm=(344, 194), ppi=141.7674418604651, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='eDP')
Display(resolution=(3840, 2160), digital_offset=(1920, 0), phys_size_mm=(697, 392), detected_phys_size_mm=(697, 392), ppi=139.93687230989957, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='HDMI-A-0')
load_system: archive_file not found: /home/maat-re/.config/superpaper/display_systems.dat
Traceback (most recent call last):
  File "/home/maat-re/.local/lib/python3.8/site-packages/superpaper/tray.py", line 509, in OnInit
    TaskBarIcon(frame)
  File "/home/maat-re/.local/lib/python3.8/site-packages/superpaper/tray.py", line 94, in __init__
    self.active_profile = self.get_profile_by_name(read_active_profile().name)
AttributeError: 'NoneType' object has no attribute 'name'
OnInit returned false, exiting...
```

**Comment by hhannine** [comment]
Thanks for the report! This is now resolved with 5df194c441e556784965bce5fd17db485ac284c9
