### ISSUE TITLE
kde no default span, cant apply changes, constant spinning

### ISSUE THREAD

**Issue by reitenth** [hhannine/superpaper#141]
i cant apply span on plasma desktop and i think that is leading to trying to apply a wallpaper, but it get stuck loading? actually i cant the spinning error on everything. running opensuse tumbleweed.

![image](https://user-images.githubusercontent.com/94771708/234682889-7473d167-d0bf-46e7-97d9-800709822e89.png)

**Comment by hhannine** [comment]
Try to see if the 2.1.0 release works? There's some initial setup issues with the newest release that I haven't gotten around to fixing.

**Comment by reitenth** [comment]
![image](https://user-images.githubusercontent.com/94771708/234904411-72d0060c-68c1-41e1-81a6-5d6bb0081d3d.png)

getting this error now on 2.10

**Comment by lhriley** [comment]
Adding a bit more context since there appear to be some actual assertion errors when I am trying this on KDE Plasma 6.0 (running within python on brew for linux):

```
me@here:~/superpaper$ python3 -m pip install --user --upgrade --break-system-packages .
Processing /home/me/superpaper
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow>=7.0.0 in /home/me/.local/lib/python3.12/site-packages (from superpaper==2.2.1) (10.2.0)
Requirement already satisfied: screeninfo>=0.6.1 in /home/me/.local/lib/python3.12/site-packages (from superpaper==2.2.1) (0.8.1)
Requirement already satisfied: numpy>=1.18.0 in /home/me/.local/lib/python3.12/site-packages (from superpaper==2.2.1) (1.26.4)
Requirement already satisfied: system_hotkey310>=1.0.5 in /home/me/.local/lib/python3.12/site-packages (from superpaper==2.2.1) (1.0.5)
Requirement already satisfied: xcffib>=0.8.0 in /home/me/.local/lib/python3.12/site-packages (from superpaper==2.2.1) (1.5.0)
Requirement already satisfied: xpybutil>=0.0.5 in /home/me/.local/lib/python3.12/site-packages (from superpaper==2.2.1) (0.0.6)
Requirement already satisfied: cffi>=1.1.0 in /home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.2_1/lib/python3.12/site-packages (from xcffib>=0.8.0->superpaper==2.2.1) (1.16.0)
Requirement already satisfied: pycparser in /home/linuxbrew/.linuxbrew/Cellar/python@3.12/3.12.2_1/lib/python3.12/site-packages (from cffi>=1.1.0->xcffib>=0.8.0->superpaper==2.2.1) (2.21)
Building wheels for collected packages: superpaper
  Building wheel for superpaper (setup.py) ... done
  Created wheel for superpaper: filename=superpaper-2.2.1-py3-none-any.whl size=287133 sha256=760416120dee806947fc95847bf38b929e101883578f29504f2ab15b9cf2d225
  Stored in directory: /tmp/pip-ephem-wheel-cache-411kxqx1/wheels/a4/02/0e/682efe871d24749635432acbe59741849e0652fba0785e380b
Successfully built superpaper
Installing collected packages: superpaper
  Attempting uninstall: superpaper
    Found existing installation: superpaper 2.2.1
    Uninstalling superpaper-2.2.1:
      Successfully uninstalled superpaper-2.2.1
Successfully installed superpaper-2.2.1
me@here:~/superpaper$ superpaper
/home/me/.local/lib/python3.12/site-packages
/home/me/.config/superpaper
/home/me/.config/superpaper/profiles
Gtk-Message: 11:44:07.942: Failed to load module "colorreload-gtk-module"

(superpaper:148596): Gtk-WARNING **: 11:44:15.799: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

(superpaper:148596): Gtk-CRITICAL **: 11:44:26.768: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/gtk/choice.cpp(303) in GetString(): invalid index

(superpaper:148596): Gtk-CRITICAL **: 11:44:39.699: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1035, in onApply
    saved_file = self.onSave(None)
                 ^^^^^^^^^^^^^^^^^
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/gtk/choice.cpp(303) in GetString(): invalid index

(superpaper:148596): Gtk-CRITICAL **: 11:44:41.028: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1035, in onApply
    saved_file = self.onSave(None)
                 ^^^^^^^^^^^^^^^^^
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/gtk/choice.cpp(303) in GetString(): invalid index

(superpaper:148596): Gtk-CRITICAL **: 11:44:41.379: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1035, in onApply
    saved_file = self.onSave(None)
                 ^^^^^^^^^^^^^^^^^
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/gtk/choice.cpp(303) in GetString(): invalid index

(superpaper:148596): Gtk-CRITICAL **: 11:44:42.179: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/gtk/choice.cpp(303) in GetString(): invalid index

(superpaper:148596): Gtk-CRITICAL **: 11:44:43.251: gtk_tree_model_iter_nth_child: assertion 'n >= 0' failed
Traceback (most recent call last):
  File "/home/me/.local/lib/python3.12/site-packages/superpaper/gui.py", line 1085, in onSave
    tmp_profile.perspective = self.ch_persp.GetString(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at ./src/gtk/choice.cpp(303) in GetString(): invalid index
```

**Comment by incansvl** [comment]
I still see these issues with the combination of-

OS: EndeavourOS 
KDE Plasma: 6.4.5
KDE Frameworks: 6.18.0
Qt: 6.9.2
Kernel: 6.16.8-arch3-1 (64-bit)
Graphics Platform: Wayland
Superpaper: v2.2.1-2

### Symptoms

1. There is no "Span" wallpaper fitting option in KDE. However I find the "Scaled" option does work, IF superpaper (SP) can be persuaded to apply the settings (see below), so I think this is just a problem with the instructions+documentation of superpaper

2. When applying settings in SP I find they will often apply, but then the UI hangs with the "ticker" icon. It is typically necessary to quit and restart SP to continue, which makes applying settings by trial and error a very slow process

3. On my machine, each time I start SP I get the warning- _Error: could not register hotkey (...). Check that it is formatted properly and valid keys._ for the following values of "..."

- cntrl+super+shift+g
- cntrl+super+shift+p
- cntrl+super+shift+w
- cntrl+super+shift+h

I have dumped out my KDE shortcut settings and I can't see any shortcut assigned to the key combos listed, and they don't actually do anything when the combos are typed, so I don't know where this clash is coming from.

**Comment by JackMBurch** [comment]
Yeah, getting the exact same thing. Maybe CLI will still work since it seems to be issues with the GUI?

**Comment by JackMBurch** [comment]
CLI works fine - definitely a GUI issue. Here's the workaround:

Go get past the `perspective` errors, switch to "Advanced span" and change the "Perspective profile" option in the bottom right from blank to default. You can then switch back to simple mode if you want and it will work.

Also, to get rid of the hotkey errors you have to fully kill superpaper from system monitor before attempting to reopen it.
