### ISSUE TITLE
Unable to start 

### ISSUE THREAD

**Issue by Findarato** [hhannine/superpaper#47]
I was able to run it once, have it all setup, but every time I try and run the app image I do not get a system tray icon.

```
/usr/lib64/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "dbus/bus.py", line 177, in activate_name_owner
  File "dbus/bus.py", line 363, in get_name_owner
  File "dbus/connection.py", line 653, in call_blocking
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: The name does not have an owner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "superpaper/wallpaper_processing.py", line 1208, in span_single_image_advanced
  File "superpaper/wallpaper_processing.py", line 1289, in set_wallpaper
  File "superpaper/wallpaper_processing.py", line 1363, in set_wallpaper_linux
  File "superpaper/wallpaper_processing.py", line 1548, in kdeplasma_actions
  File "dbus/bus.py", line 243, in get_object
  File "dbus/proxies.py", line 250, in __init__
  File "dbus/bus.py", line 182, in activate_name_owner
  File "dbus/bus.py", line 280, in start_service_by_name
  File "dbus/connection.py", line 653, in call_blocking
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

I have tried it in both I3 and Gnome.

**Comment by hhannine** [comment]
Unfortunately the KDE detection has become to sensitive in the recent release and its trying to run KDE code. Interesting that it did work first.

In the meantime before I can get a new release out a work around is to run it with KDE_FULL_SESSION='' ./superpaper

**Comment by Findarato** [comment]
Just adding a note based on your comments
```
KDE_FULL_SESSION='' ./superpaper
/tmp/.mount_superpm6kxCd/usr
/home/joe/.config/superpaper
/home/joe/.config/superpaper/profiles
/usr/lib64/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
10:19:47 AM: Debug: Failed to connect to session manager: None of the authentication protocols specified are supported
```

**Comment by hhannine** [comment]
Does it run like before otherwise?

**Comment by Findarato** [comment]
Just an update on this.  I got the newest version from the site Just now and I do not see any tray icons.  I am using Gnome 3.36

```
/tmp/.mount_SuperpvFs5kq/usr
/home/joe/.config/superpaper
/home/joe/.config/superpaper/profiles
/usr/lib64/gio/modules/libgvfsdbus.so: undefined symbol: g_date_time_format_iso8601
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
07:36:58 PM: Debug: Failed to connect to session manager: None of the authentication protocols specified are supported
Unhandled exception in thread started by <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7f556093deb8>>
Traceback (most recent call last):
  File "system_hotkey/system_hotkey.py", line 756, in _xcb_the_grab
  File "xcffib/__init__.py", line 339, in check
  File "xcffib/__init__.py", line 571, in wrapper
  File "xcffib/__init__.py", line 680, in request_check
  File "xcffib/__init__.py", line 648, in _process_error
xcffib.xproto.AccessError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "system_hotkey/util.py", line 37, in call_functions
  File "system_hotkey/system_hotkey.py", line 307, in register
  File "system_hotkey/system_hotkey.py", line 763, in _xcb_the_grab
system_hotkey.system_hotkey.SystemRegisterError: The bind could be in use elsewhere: w
```

I have [Kstatusnotifieritem/appindicator](https://extensions.gnome.org/extension/615/appindicator-support/) support installed.  If there is a different one please let me know which I should use to access the indicator on GNOME.
