### ISSUE TITLE
Not openning on Manjaro Stable (Gnome)

### ISSUE THREAD

**Issue by tiotrom** [hhannine/superpaper#53]
Here's the output:

```
superpaper
/usr/lib/python3.8/site-packages
/home/tio/.config/superpaper
/home/tio/.config/superpaper/profiles
Traceback (most recent call last):
  File "/usr/bin/superpaper", line 11, in <module>
    load_entry_point('superpaper==2.0.2', 'console_scripts', 'superpaper')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/superpaper/__main__.py", line 13, in <module>
    from superpaper.cli import cli_logic
  File "/usr/lib/python3.8/site-packages/superpaper/cli.py", line 8, in <module>
    from superpaper.data import CLIProfileData
  File "/usr/lib/python3.8/site-packages/superpaper/data.py", line 15, in <module>
    import superpaper.wallpaper_processing as wpproc
  File "/usr/lib/python3.8/site-packages/superpaper/wallpaper_processing.py", line 19, in <module>
    from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (/usr/lib/python3.8/site-packages/PIL/__init__.py)

```

**Comment by tiotrom** [comment]
Ok. So the appimage works - what I was testing is the AUR https://aur.archlinux.org/packages/superpaper. I guess I'll report it there.

**Comment by hhannine** [comment]
Thanks for reporting it there. The AUR package isn't maintained by me and this has already come up once before.
