### ISSUE TITLE
Mismatch with KDE Plasma Version 5.20.4/ Python 3.9

### ISSUE THREAD

**Issue by kinoegit** [hhannine/superpaper#75]
After update of Plasma: superpaper does not run
Starting via bash:
```
superpaper
/usr/lib/python3.9/site-packages
/home/kinoe/.config/superpaper
/home/kinoe/.config/superpaper/profiles
21:47:16: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8).
Traceback (most recent call last):
  File "/usr/bin/superpaper", line 33, in <module>
    sys.exit(load_entry_point('superpaper==2.1.0', 'console_scripts', 'superpaper')())
  File "/usr/bin/superpaper", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/superpaper/__main__.py", line 13, in <module>
    from superpaper.cli import cli_logic
  File "/usr/lib/python3.9/site-packages/superpaper/cli.py", line 8, in <module>
    from superpaper.data import CLIProfileData
  File "/usr/lib/python3.9/site-packages/superpaper/data.py", line 15, in <module>
    import superpaper.wallpaper_processing as wpproc
  File "/usr/lib/python3.9/site-packages/superpaper/wallpaper_processing.py", line 20, in <module>
    from screeninfo import get_monitors
ModuleNotFoundError: No module named 'screeninfo'
```
I did a reinstallation to no avail

Operating System: Arch Linux
KDE Plasma Version: 5.20.4
KDE Frameworks Version: 5.76.0
Qt Version: 5.15.2
Kernel Version: 5.9.11-arch2-1
OS Type: 64-bit
Processors: 12 × Intel® Core™ i5-10600 CPU @ 3.30GHz
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by hhannine** [comment]
Thanks. I'm seeing the same mismatch warning but it is not causing any breakage as far as I can tell.

However I see that the dependency 'screeninfo' is not installed for some reason. Are you using the pip installation of Superpaper or something else? If it's pip you're using, you can install screeninfo with pip.

**Comment by kinoegit** [comment]
Thanks for the tip. I uninstalled superpaper and reinstalled it via `python3 -m pip install . --user -U` with full success.
