### ISSUE TITLE
Application runs, won't change wallpaper - Xubuntu 20.04 new install

### ISSUE THREAD

**Issue by bonelifer** [hhannine/superpaper#79]
**Describe the bug**
Application runs, but doesn't change wallpaper. It can see the wallpapers as they display when you choose the profile in wallpaper configuration, but it won't load the wallpaper, using Next wallpaper, etc. I've tried restarting my laptop. This is a clean install of Xubuntu 20.04. On my prior Xubuntu 18.04, this all worked.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Desktop Environment on Linux: Xubuntu (XFCE)
 - Superpaper package & version: AppImage 2.1.0

Logging / debugging contents:
```
william@william:~/Applications$ ./Superpaper-2.1.0-x86_64_51e19cc71c8fa6cb07593b1525476c7f.AppImage -d
/tmp/.mount_SuperpGzUsfE/usr
/home/william/.config/superpaper
/home/william/.config/superpaper/profiles
None
None
None
None
None
None
True

(Superpaper-2.1.0-x86_64_51e19cc71c8fa6cb07593b1525476c7f.AppImage:41149): GdkPixbuf-WARNING **: 21:32:29.511: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
09:32:29 PM: Debug: Failed to connect to session manager: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
use_hotkeys: True
hk_binding_next: ('control', 'super', 'w')
hk_binding_pause: ('control', 'super', 'shift', 'p')
get_display_data output: NUM_DISPLAYS = 1, RES_ARR = [(1280, 800)], OFF_ARR = [(0, 0)]
Display(resolution=(1280, 800), digital_offset=(0, 0), phys_size_mm=(331, 207), detected_phys_size_mm=(331, 207), ppi=98.22356495468279, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='LVDS-1')
load_system: archive_file not found: /home/william/.config/superpaper/display_systems.dat
START Listing profiles for menu.
perspective preset: default
Listed profile: default
END Listing profiles for menu.
read profile name from 'running_profile': default
perspective preset: default
get_display_data output: NUM_DISPLAYS = 1, RES_ARR = [(1280, 800)], OFF_ARR = [(0, 0)]
Display(resolution=(1280, 800), digital_offset=(0, 0), phys_size_mm=(331, 207), detected_phys_size_mm=(331, 207), ppi=98.22356495468279, ppi_norm_resolution=None, ppi_norm_offset=None, ppi_norm_bezels=(0, 0), perspective_angles=(0, 0), name='LVDS-1')
load_system: archive_file not found: /home/william/.config/superpaper/display_systems.dat
running profile job with profile: default
Running a one-off wallpaper change.
['/media/william/Data2/Wallpaper/vladstudio_greenriver.jpg']
get_ppi_norm_offsets: [(0, 0)]
get_ppi_norm_crops: [(0, 0, 1280, 800)]
G_A_DSYS.use_perspective: True, prof.perspective: default
perspective preset: default
Listed profile: default
Registering binding:                                 None for profile: default
Canvas size: [1280, 800]
file:///home/william/.cache/superpaper/temp/default-b.png
DESKTOP_SESSION is: 'xubuntu'
Removing images matching with: 'default-a-crop'
```

**Comment by hhannine** [comment]
Thank you for the detailed bug report, it is an especially important detail that this was working on 18.04. It looks like a new version of XFCE was introduced in 19.10, and could have introduced changes to how the wallpaper setting works on XFCE. This could be related to #45, which turned out to be a hard problem..

Would you mind running these terminal commands and posting their outputs?
`xfconf-query -c xfce4-desktop -p /backdrop -l`
and
`xfconf-query -c displays -l`

**Comment by bonelifer** [comment]
xfconf-query -c xfce4-desktop -p /backdrop -l
```
/backdrop/screen0/monitor0/image-path
/backdrop/screen0/monitor0/image-show
/backdrop/screen0/monitor0/image-style
/backdrop/screen0/monitor1/image-path
/backdrop/screen0/monitor1/image-show
/backdrop/screen0/monitor1/image-style
/backdrop/screen0/monitor2/image-path
/backdrop/screen0/monitor2/image-show
/backdrop/screen0/monitor2/image-style
/backdrop/screen0/monitor3/image-path
/backdrop/screen0/monitor3/image-show
/backdrop/screen0/monitor3/image-style
/backdrop/screen0/monitorLVDS-1/workspace0/color-style
/backdrop/screen0/monitorLVDS-1/workspace0/image-style
/backdrop/screen0/monitorLVDS-1/workspace0/last-image
/backdrop/single-workspace-mode
/backdrop/single-workspace-number
```
xfconf-query -c displays -l
```
/ActiveProfile
/Default/LVDS-1
/Default/LVDS-1/Active
/Default/LVDS-1/EDID
/Default/LVDS-1/Position/X
/Default/LVDS-1/Position/Y
/Default/LVDS-1/Primary
/Default/LVDS-1/Reflection
/Default/LVDS-1/RefreshRate
/Default/LVDS-1/Resolution
/Default/LVDS-1/Rotation
/Fallback/LVDS-1
/Fallback/LVDS-1/Active
/Fallback/LVDS-1/EDID
/Fallback/LVDS-1/Position/X
/Fallback/LVDS-1/Position/Y
/Fallback/LVDS-1/Primary
/Fallback/LVDS-1/Reflection
/Fallback/LVDS-1/RefreshRate
/Fallback/LVDS-1/Resolution
/Fallback/LVDS-1/Rotation
```
I'd also say that "gdk-pixbuf-query-loaders" doesn't exist on 20.04.

**Comment by bonelifer** [comment]
Have you had a chance to look into this?

**Comment by hhannine** [comment]
Yes I've looked at this, I would've needed to setup a virtual machine of Xubuntu to test, but I've been busy. Problem is that I don't understand the /backdrop/screen0/monitor<X> naming structure.

One option I ran into would be to try to use [this feature](https://www.ubuntubuzz.com/2012/01/enable-multi-display-wallpaper-on-xfce.html) to have XFCE hopefully span the image automatically. If that would work, then XFCE could use the same code that other OSs use and then the only thing that would need to be figured out is how to set the single image used to span the image.

**Comment by cocoonkid** [comment]
I have the same Issue running on Arch Linux Xfce.
Is my output for the commands above helpful too? Then I will supply them if requested.

**Comment by cocoonkid** [comment]
I just tested Hydrapaper which has the same Issue.  Looks like it really is about xfce.

**Comment by hhannine** [comment]
Please do supply the outputs.

Yes I think the issue is that a recent version of XFCE has changed the names of the monitors in the above output. In the line
`/backdrop/screen0/monitorLVDS-1/workspace0/last-image`
the monitor name used to be of the form `monitor<int>`, which is isn't anymore. And I've seen output where the monitor name does _not_ start with `monitorLVDS`, so some method for the correct discovery of the monitor names is needed.

**Comment by cocoonkid** [comment]
xfconf-query -c xfce4-desktop -p /backdrop -l

```
❯ xfconf-query -c xfce4-desktop -p /backdrop -l
/backdrop/screen0/monitor0/workspace0/backdrop-cycle-enable
/backdrop/screen0/monitor0/workspace0/color-style
/backdrop/screen0/monitor0/workspace0/image-style
/backdrop/screen0/monitor0/workspace0/last-image
/backdrop/screen0/monitor0/workspace1/color-style
/backdrop/screen0/monitor0/workspace1/image-style
/backdrop/screen0/monitor0/workspace1/last-image
/backdrop/screen0/monitor0/workspace2/color-style
/backdrop/screen0/monitor0/workspace2/image-style
/backdrop/screen0/monitor0/workspace2/last-image
/backdrop/screen0/monitor0/workspace3/color-style
/backdrop/screen0/monitor0/workspace3/image-style
/backdrop/screen0/monitor0/workspace3/last-image
/backdrop/screen0/monitor1/workspace0/color-style
/backdrop/screen0/monitor1/workspace0/image-style
/backdrop/screen0/monitor1/workspace0/last-image
/backdrop/screen0/monitor1/workspace1/color-style
/backdrop/screen0/monitor1/workspace1/image-style
/backdrop/screen0/monitor1/workspace1/last-image
/backdrop/screen0/monitor1/workspace2/color-style
/backdrop/screen0/monitor1/workspace2/image-style
/backdrop/screen0/monitor1/workspace2/last-image
/backdrop/screen0/monitor1/workspace3/color-style
/backdrop/screen0/monitor1/workspace3/image-style
/backdrop/screen0/monitor1/workspace3/last-image
/backdrop/screen0/monitorDisplayPort-2/workspace0/color-style
/backdrop/screen0/monitorDisplayPort-2/workspace0/image-style
/backdrop/screen0/monitorDisplayPort-2/workspace0/last-image
/backdrop/screen0/monitorDisplayPort-2/workspace1/color-style
/backdrop/screen0/monitorDisplayPort-2/workspace1/image-style
/backdrop/screen0/monitorDisplayPort-2/workspace1/last-image
/backdrop/screen0/monitorDisplayPort-2/workspace2/color-style
/backdrop/screen0/monitorDisplayPort-2/workspace2/image-style
/backdrop/screen0/monitorDisplayPort-2/workspace2/last-image
/backdrop/screen0/monitorDisplayPort-2/workspace3/color-style
/backdrop/screen0/monitorDisplayPort-2/workspace3/image-style
/backdrop/screen0/monitorDisplayPort-2/workspace3/last-image
/backdrop/screen0/monitorDP-1/workspace0/color-style
/backdrop/screen0/monitorDP-1/workspace0/image-style
/backdrop/screen0/monitorDP-1/workspace0/last-image
/backdrop/screen0/monitorDP-1/workspace1/color-style
/backdrop/screen0/monitorDP-1/workspace1/image-style
/backdrop/screen0/monitorDP-1/workspace1/last-image
/backdrop/screen0/monitorDP-1/workspace2/color-style
/backdrop/screen0/monitorDP-1/workspace2/image-style
/backdrop/screen0/monitorDP-1/workspace2/last-image
/backdrop/screen0/monitorDP-1/workspace3/color-style
/backdrop/screen0/monitorDP-1/workspace3/image-style
/backdrop/screen0/monitorDP-1/workspace3/last-image
/backdrop/screen0/monitorDP-3/workspace0/color-style
/backdrop/screen0/monitorDP-3/workspace0/image-style
/backdrop/screen0/monitorDP-3/workspace0/last-image
/backdrop/screen0/monitorDP-4/workspace0/color-style
/backdrop/screen0/monitorDP-4/workspace0/image-style
/backdrop/screen0/monitorDP-4/workspace0/last-image
/backdrop/screen0/monitorDVI-D-0/workspace0/color-style
/backdrop/screen0/monitorDVI-D-0/workspace0/image-style
/backdrop/screen0/monitorDVI-D-0/workspace0/last-image
/backdrop/screen0/monitorDVI-D-0/workspace1/color-style
/backdrop/screen0/monitorDVI-D-0/workspace1/image-style
/backdrop/screen0/monitorDVI-D-0/workspace1/last-image
/backdrop/screen0/monitorDVI-D-0/workspace2/color-style
/backdrop/screen0/monitorDVI-D-0/workspace2/image-style
/backdrop/screen0/monitorDVI-D-0/workspace2/last-image
/backdrop/screen0/monitorDVI-D-0/workspace3/color-style
/backdrop/screen0/monitorDVI-D-0/workspace3/image-style
/backdrop/screen0/monitorDVI-D-0/workspace3/last-image
/backdrop/screen0/monitorDVI-D-1/workspace0/color-style
/backdrop/screen0/monitorDVI-D-1/workspace0/image-style
/backdrop/screen0/monitorDVI-D-1/workspace0/last-image
/backdrop/screen0/monitorDVI-D-1/workspace1/color-style
/backdrop/screen0/monitorDVI-D-1/workspace1/image-style
/backdrop/screen0/monitorDVI-D-1/workspace1/last-image
/backdrop/screen0/monitorDVI-D-1/workspace2/color-style
/backdrop/screen0/monitorDVI-D-1/workspace2/image-style
/backdrop/screen0/monitorDVI-D-1/workspace2/last-image
/backdrop/screen0/monitorDVI-D-1/workspace3/color-style
/backdrop/screen0/monitorDVI-D-1/workspace3/image-style
/backdrop/screen0/monitorDVI-D-1/workspace3/last-image
/backdrop/screen0/monitorDVI-I-1/workspace0/color-style
/backdrop/screen0/monitorDVI-I-1/workspace0/image-style
/backdrop/screen0/monitorDVI-I-1/workspace0/last-image
/backdrop/screen0/monitorDVI-I-1/workspace1/color-style
/backdrop/screen0/monitorDVI-I-1/workspace1/image-style
/backdrop/screen0/monitorDVI-I-1/workspace1/last-image
/backdrop/screen0/monitorDVI-I-1/workspace2/color-style
/backdrop/screen0/monitorDVI-I-1/workspace2/image-style
/backdrop/screen0/monitorDVI-I-1/workspace2/last-image
/backdrop/screen0/monitorDVI-I-1/workspace3/color-style
/backdrop/screen0/monitorDVI-I-1/workspace3/image-style
/backdrop/screen0/monitorDVI-I-1/workspace3/last-image
/backdrop/screen0/monitoreDP1/workspace0/color-style
/backdrop/screen0/monitoreDP1/workspace0/image-style
/backdrop/screen0/monitoreDP1/workspace0/last-image
/backdrop/screen0/monitoreDP1/workspace1/color-style
/backdrop/screen0/monitoreDP1/workspace1/image-style
/backdrop/screen0/monitoreDP1/workspace1/last-image
/backdrop/screen0/monitoreDP1/workspace2/color-style
/backdrop/screen0/monitoreDP1/workspace2/image-style
/backdrop/screen0/monitoreDP1/workspace2/last-image
/backdrop/screen0/monitoreDP1/workspace3/color-style
/backdrop/screen0/monitoreDP1/workspace3/image-style
/backdrop/screen0/monitoreDP1/workspace3/last-image
/backdrop/screen0/monitorHDMI-1/workspace0/color-style
/backdrop/screen0/monitorHDMI1/workspace0/color-style
/backdrop/screen0/monitorHDMI-1/workspace0/image-style
/backdrop/screen0/monitorHDMI1/workspace0/image-style
/backdrop/screen0/monitorHDMI-1/workspace0/last-image
/backdrop/screen0/monitorHDMI1/workspace0/last-image
/backdrop/screen0/monitorHDMI1/workspace1/color-style
/backdrop/screen0/monitorHDMI1/workspace1/image-style
/backdrop/screen0/monitorHDMI1/workspace1/last-image
/backdrop/screen0/monitorHDMI1/workspace2/color-style
/backdrop/screen0/monitorHDMI1/workspace2/image-style
/backdrop/screen0/monitorHDMI1/workspace2/last-image
/backdrop/screen0/monitorHDMI1/workspace3/color-style
/backdrop/screen0/monitorHDMI1/workspace3/image-style
/backdrop/screen0/monitorHDMI1/workspace3/last-image
/backdrop/screen0/monitorHDMI2/workspace0/color-style
/backdrop/screen0/monitorHDMI2/workspace0/image-style
/backdrop/screen0/monitorHDMI2/workspace0/last-image
/backdrop/screen0/monitorHDMI2/workspace1/color-style
/backdrop/screen0/monitorHDMI2/workspace1/image-style
/backdrop/screen0/monitorHDMI2/workspace1/last-image
/backdrop/screen0/monitorHDMI2/workspace2/color-style
/backdrop/screen0/monitorHDMI2/workspace2/image-style
/backdrop/screen0/monitorHDMI2/workspace2/last-image
/backdrop/screen0/monitorHDMI2/workspace3/color-style
/backdrop/screen0/monitorHDMI2/workspace3/image-style
/backdrop/screen0/monitorHDMI2/workspace3/last-image
/backdrop/screen0/monitorHDMI-A-0/workspace0/color-style
/backdrop/screen0/monitorHDMI-A-0/workspace0/image-style
/backdrop/screen0/monitorHDMI-A-0/workspace0/last-image
/backdrop/screen0/monitorHDMI-A-0/workspace1/color-style
/backdrop/screen0/monitorHDMI-A-0/workspace1/image-style
/backdrop/screen0/monitorHDMI-A-0/workspace1/last-image
/backdrop/screen0/monitorHDMI-A-0/workspace2/color-style
/backdrop/screen0/monitorHDMI-A-0/workspace2/image-style
/backdrop/screen0/monitorHDMI-A-0/workspace2/last-image
/backdrop/screen0/monitorHDMI-A-0/workspace3/color-style
/backdrop/screen0/monitorHDMI-A-0/workspace3/image-style
/backdrop/screen0/monitorHDMI-A-0/workspace3/last-image
/backdrop/screen0/monitorLVDS1/workspace0/color-style
/backdrop/screen0/monitorLVDS1/workspace0/image-style
/backdrop/screen0/monitorLVDS1/workspace0/last-image
/backdrop/screen0/monitorLVDS1/workspace1/color-style
/backdrop/screen0/monitorLVDS1/workspace1/image-style
/backdrop/screen0/monitorLVDS1/workspace1/last-image
/backdrop/screen0/monitorLVDS1/workspace2/color-style
/backdrop/screen0/monitorLVDS1/workspace2/image-style
/backdrop/screen0/monitorLVDS1/workspace2/last-image
/backdrop/screen0/monitorLVDS1/workspace3/color-style
/backdrop/screen0/monitorLVDS1/workspace3/image-style
/backdrop/screen0/monitorLVDS1/workspace3/last-image
/backdrop/screen0/monitorVGA-1/workspace0/color-style
/backdrop/screen0/monitorVGA-1/workspace0/image-style
/backdrop/screen0/monitorVGA-1/workspace0/last-image
/backdrop/screen0/monitorVGA-1/workspace1/color-style
/backdrop/screen0/monitorVGA-1/workspace1/image-style
/backdrop/screen0/monitorVGA-1/workspace1/last-image
/backdrop/screen0/monitorVGA-1/workspace2/color-style
/backdrop/screen0/monitorVGA-1/workspace2/image-style
/backdrop/screen0/monitorVGA-1/workspace2/last-image
/backdrop/screen0/monitorVGA-1/workspace3/color-style
/backdrop/screen0/monitorVGA-1/workspace3/image-style
/backdrop/screen0/monitorVGA-1/workspace3/last-image
/backdrop/single-workspace-mode
```

```
/589c22335a381f122d129225f5c0ba3056ed5811
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Active
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/EDID
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Position/X
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Position/Y
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Primary
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Reflection
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/RefreshRate
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Resolution
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Rotation
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Scale/X
/589c22335a381f122d129225f5c0ba3056ed5811/DisplayPort-2/Scale/Y
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Active
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/EDID
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Position/X
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Position/Y
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Primary
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Reflection
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/RefreshRate
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Resolution
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Rotation
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Scale/X
/589c22335a381f122d129225f5c0ba3056ed5811/HDMI-A-0/Scale/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Active
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/EDID
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Position/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Position/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Primary
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Reflection
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/RefreshRate
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Resolution
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Rotation
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Scale/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/DisplayPort-2/Scale/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Active
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/EDID
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Position/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Position/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Primary
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Reflection
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/RefreshRate
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Resolution
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Rotation
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Scale/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/DP-3/Scale/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Active
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/EDID
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Position/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Position/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Primary
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Reflection
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/RefreshRate
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Resolution
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Rotation
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Scale/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-1/Scale/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Active
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/EDID
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Position/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Position/Y
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Primary
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Reflection
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/RefreshRate
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Resolution
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Rotation
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Scale/X
/7505d64a54e061b7acd54ccd58b49dc43500b635/HDMI-A-0/Scale/Y
/ActiveProfile
/AutoEnableProfiles
/Default/DisplayPort-2
/Default/DisplayPort-2/Active
/Default/DisplayPort-2/EDID
/Default/DisplayPort-2/Position/X
/Default/DisplayPort-2/Position/Y
/Default/DisplayPort-2/Primary
/Default/DisplayPort-2/Reflection
/Default/DisplayPort-2/RefreshRate
/Default/DisplayPort-2/Resolution
/Default/DisplayPort-2/Rotation
/Default/DisplayPort-2/Scale/X
/Default/DisplayPort-2/Scale/Y
/Default/DP-1
/Default/DP-1/Active
/Default/DP-1/EDID
/Default/DP-1/Position/X
/Default/DP-1/Position/Y
/Default/DP-1/Primary
/Default/DP-1/Reflection
/Default/DP-1/RefreshRate
/Default/DP-1/Resolution
/Default/DP-1/Rotation
/Default/DP-1/Scale/X
/Default/DP-1/Scale/Y
/Default/DP-3
/Default/DP-3/Active
/Default/DP-3/EDID
/Default/DP-3/Position/X
/Default/DP-3/Position/Y
/Default/DP-3/Primary
/Default/DP-3/Reflection
/Default/DP-3/RefreshRate
/Default/DP-3/Resolution
/Default/DP-3/Rotation
/Default/DP-3/Scale/X
/Default/DP-3/Scale/Y
/Default/DP-4
/Default/DP-4/Active
/Default/DP-4/EDID
/Default/DP-4/Position/X
/Default/DP-4/Position/Y
/Default/DP-4/Primary
/Default/DP-4/Reflection
/Default/DP-4/RefreshRate
/Default/DP-4/Resolution
/Default/DP-4/Rotation
/Default/DP-4/Scale/X
/Default/DP-4/Scale/Y
/Default/eDP1
/Default/eDP1/Active
/Default/eDP1/EDID
/Default/eDP1/Position/X
/Default/eDP1/Position/Y
/Default/eDP1/Primary
/Default/eDP1/Reflection
/Default/eDP1/RefreshRate
/Default/eDP1/Resolution
/Default/eDP1/Rotation
/Default/HDMI-1
/Default/HDMI-1/Active
/Default/HDMI-1/EDID
/Default/HDMI-1/Position/X
/Default/HDMI-1/Position/Y
/Default/HDMI-1/Primary
/Default/HDMI-1/Reflection
/Default/HDMI-1/RefreshRate
/Default/HDMI-1/Resolution
/Default/HDMI-1/Rotation
/Default/HDMI-1/Scale/X
/Default/HDMI-1/Scale/Y
/Default/HDMI-A-0
/Default/HDMI-A-0/Active
/Default/HDMI-A-0/EDID
/Default/HDMI-A-0/Position/X
/Default/HDMI-A-0/Position/Y
/Default/HDMI-A-0/Primary
/Default/HDMI-A-0/Reflection
/Default/HDMI-A-0/RefreshRate
/Default/HDMI-A-0/Resolution
/Default/HDMI-A-0/Rotation
/Default/HDMI-A-0/Scale/X
/Default/HDMI-A-0/Scale/Y
/Fallback/DisplayPort-2
/Fallback/DisplayPort-2/Active
/Fallback/DisplayPort-2/EDID
/Fallback/DisplayPort-2/Position/X
/Fallback/DisplayPort-2/Position/Y
/Fallback/DisplayPort-2/Primary
/Fallback/DisplayPort-2/Reflection
/Fallback/DisplayPort-2/RefreshRate
/Fallback/DisplayPort-2/Resolution
/Fallback/DisplayPort-2/Rotation
/Fallback/DisplayPort-2/Scale/X
/Fallback/DisplayPort-2/Scale/Y
/Fallback/DP-1
/Fallback/DP-1/Active
/Fallback/DP-1/EDID
/Fallback/DP-1/Position/X
/Fallback/DP-1/Position/Y
/Fallback/DP-1/Primary
/Fallback/DP-1/Reflection
/Fallback/DP-1/RefreshRate
/Fallback/DP-1/Resolution
/Fallback/DP-1/Rotation
/Fallback/DP-1/Scale/X
/Fallback/DP-1/Scale/Y
/Fallback/DP-3
/Fallback/DP-3/Active
/Fallback/DP-3/EDID
/Fallback/DP-3/Position/X
/Fallback/DP-3/Position/Y
/Fallback/DP-3/Primary
/Fallback/DP-3/Reflection
/Fallback/DP-3/RefreshRate
/Fallback/DP-3/Resolution
/Fallback/DP-3/Rotation
/Fallback/DP-3/Scale/X
/Fallback/DP-3/Scale/Y
/Fallback/DP-4
/Fallback/DP-4/Active
/Fallback/DP-4/EDID
/Fallback/DP-4/Position/X
/Fallback/DP-4/Position/Y
/Fallback/DP-4/Primary
/Fallback/DP-4/Reflection
/Fallback/DP-4/RefreshRate
/Fallback/DP-4/Resolution
/Fallback/DP-4/Rotation
/Fallback/DP-4/Scale/X
/Fallback/DP-4/Scale/Y
/Fallback/eDP1
/Fallback/eDP1/Active
/Fallback/eDP1/EDID
/Fallback/eDP1/Position/X
/Fallback/eDP1/Position/Y
/Fallback/eDP1/Primary
/Fallback/eDP1/Reflection
/Fallback/eDP1/RefreshRate
/Fallback/eDP1/Resolution
/Fallback/eDP1/Rotation
/Fallback/HDMI-1
/Fallback/HDMI-1/Active
/Fallback/HDMI-1/EDID
/Fallback/HDMI-1/Position/X
/Fallback/HDMI-1/Position/Y
/Fallback/HDMI-1/Primary
/Fallback/HDMI-1/Reflection
/Fallback/HDMI-1/RefreshRate
/Fallback/HDMI-1/Resolution
/Fallback/HDMI-1/Rotation
/Fallback/HDMI-1/Scale/X
/Fallback/HDMI-1/Scale/Y
/Fallback/HDMI-A-0
/Fallback/HDMI-A-0/Active
/Fallback/HDMI-A-0/EDID
/Fallback/HDMI-A-0/Position/X
/Fallback/HDMI-A-0/Position/Y
/Fallback/HDMI-A-0/Primary
/Fallback/HDMI-A-0/Reflection
/Fallback/HDMI-A-0/RefreshRate
/Fallback/HDMI-A-0/Resolution
/Fallback/HDMI-A-0/Rotation
/Fallback/HDMI-A-0/Scale/X
/Fallback/HDMI-A-0/Scale/Y
/IdentityPopups
/Notify
```

```


```

**Comment by bonelifer** [comment]
I've switched to Variety since posting this: https://github.com/varietywalls/variety

**Comment by hhannine** [comment]
Ok, thanks for letting me know. I had glance and unfortunately the way Variety interfaces with XFCE, they can't support multiple monitors. I have tentative plans to try to fix this later in the summer.

**Comment by Stef500** [comment]
Hi hhannine, 
I've the same issue with Cinamon 5.0.5 (Linux Mint 20.2) :

```
Gtk-Message: 21:37:13.751: Failed to load module "xapp-gtk3-module"

(Superpaper-2.0.2-x86_64.AppImage:34278): GdkPixbuf-WARNING **: 21:37:13.757: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
09:37:13 PM: Debug: Failed to connect to session manager: None of the authentication protocols specified are supported
Unhandled exception in thread started by <bound method CallSerializer.call_functions of <system_hotkey.util.CallSerializer object at 0x7fa9b7ccd940>>
Traceback (most recent call last):
  File "system_hotkey/system_hotkey.py", line 756, in _xcb_the_grab
  File "xcffib/__init__.py", line 339, in check
  File "xcffib/__init__.py", line 571, in wrapper
  File "xcffib/__init__.py", line 680, in request_check
  File "xcffib/__init__.py", line 648, in _process_error
xcffib.xproto.AccessError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "system_hotkey/util.py", line 37, in call_functions
  File "system_hotkey/system_hotkey.py", line 307, in register
  File "system_hotkey/system_hotkey.py", line 763, in _xcb_the_grab
system_hotkey.system_hotkey.SystemRegisterError: The bind could be in use elsewhere: w
GLib-GIO-Message: 21:37:15.662: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
GLib-GIO-Message: 21:37:33.013: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
```

Can you please help me ?

**Comment by hhannine** [comment]
Is the issue that the wallpaper won't change? Then check the known issues page about the glib-gio https://github.com/hhannine/superpaper/blob/master/docs/known-issues.md

Other errors about hotkeys sound like you have more than one instance of superpaper running.

**Comment by Stef500** [comment]
Thanks a lot, it was the glib-gio. It's working now!
Great app, kudos !

**Comment by hhannine** [comment]
The plan to try to fix this is somewhat as follows:

-find the primary display name:
`xfconf-query -c displays -p /Default/Virtual1/Primary` > true
-set the image style to span all displays:
`xfconf-query -c xfce4-displays -p /backdrop/screen0/monitorVirtual1/workspace0/image-style -s 6`
-and finally set the wallpaper for the primary display
`xfconf-query -c xfce4-displays -p /backdrop/screen0/monitorVirtual1/workspace0/last-style -s /full/path/to/image`

**Comment by hhannine** [comment]
I seem to have been able to fix this based on short testing in virtual machine: commit 5405e36.

Any testing would be greatly appreciated.
