### ISSUE TITLE
Freezing when applying images on first run, crashes after subsequent launch

### ISSUE THREAD

**Issue by zer0exia** [hhannine/superpaper#82]
The app will launch, but freeze on clicking "apply" on the first run, and I have to terminate the program. Subsequent launch will crash the program. However, I noticed that depending on which setting I choose, the error on the terminal will produce different output. I deleted the superpaper folder in .config before each new successful launches.

The error in terminal on subsequent launches : 

If I set as "simple span"
```
/tmp/.mount_SuperpcmzI38/usr
/home/user/.config/superpaper
/home/user/.config/superpaper/profiles
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
07:58:15 AM: Debug: Failed to connect to session manager: None of the authentication protocols specified are supported

(Superpaper-2.1.0-x86_64.AppImage:69518): Gtk-WARNING **: 07:58:15.456: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
Superpaper-2.1.0-x86_64.AppImage: xcb_io.c:643: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1]    69512 abort (core dumped)  ./Superpaper-2.1.0-x86_64.AppImage`
```

If I set as "advanced span"
```
Failed to write all bytes for mpl-data/fonts/afm/pncr8a.afm
fwrite: No space left on device
```

If I set as "separate image"
```
`/tmp/.mount_SuperpZqIqqk/usr
/home/user/.config/superpaper
/home/user/.config/superpaper/profiles
/usr/lib/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib64/gio/modules/libgvfsdbus.so
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
08:01:26 AM: Debug: Failed to connect to session manager: None of the authentication protocols specified are supported

(Superpaper-2.1.0-x86_64.AppImage:69857): Gtk-WARNING **: 08:01:26.863: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

(Superpaper-2.1.0-x86_64.AppImage:69857): Gdk-ERROR **: 08:01:32.551: The program 'Superpaper-2.1.0-x86_64.AppImage' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 11094 error_code 2 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
[1]    69850 trace trap (core dumped)  ./Superpaper-2.1.0-x86_64.AppImage`
```

**Desktop Information : **
 - OS: EndeavorOS ; 5.11.10-arch1-1
 - Gnome-shell 3.38
 - X11

**Comment by hhannine** [comment]
Very weird, unfortunately the error messages are quite unhelpful. Though it looks like in the advanced span case it didn't even run. Feasibly the Appimage built on 18.04 Ubuntu is too out of date to run on modern Arch, not sure. You could try to run the package from AUR? AFAIK it works. Or the only native way that I support myself is to install from pip, could have better results than the appimage.

**Comment by zer0exia** [comment]
I've tested with the version from pip installation. The same issue occurred. I did try out of curiosity the solution from known issues for Pop!_OS by running the program with `DESKTOP_SESSION=gnome superpaper`. The app did not crash on startup, nor did it freeze while applying images. However the wallpapers aren't loaded, even when I clicked the profile name in the system tray or by pressing hotkeys.

The output in the terminal should it be relevant : 
```
/home/user/.local/lib/python3.9/site-packages
/home/user/.config/superpaper
/home/user/.config/superpaper/profiles
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fate/.local/lib/python3.9/site-packages/superpaper/wallpaper_processing.py", line 1333, in set_multi_image_wallpaper
    set_wallpaper(outputfile)
  File "/home/fate/.local/lib/python3.9/site-packages/superpaper/wallpaper_processing.py", line 1376, in set_wallpaper
    set_wallpaper_linux(outputfile)
  File "/home/fate/.local/lib/python3.9/site-packages/superpaper/wallpaper_processing.py", line 1420, in set_wallpaper_linux
    subprocess.run(formatted_command)
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gnome'
```

**Comment by hhannine** [comment]
Would you run `DESKTOP_SESSION=gnome superpaper -d` and post the debugging output?

**Comment by zer0exia** [comment]
While you're replying, I've deleted the config folder and relaunch the app again with that command. The wallpapers are loaded now, not really sure what went wrong before.  It's seems that I may have the same issues as Pop!_OS (maybe Gnome issue in general?). I think this can be closed now since the workaround did work. Thank you for your response ( and also for this awesome app)
